In [41]:
import numpy as np
import numpy.linalg as LA

#### Придумайте матрицы, которые обладают следующими свойствами:

#### a)Диагональная, ортогональная, но не единичная(!)

In [19]:
a = np.array([[-1,  0,  0],
              [ 0, -1,  0],
              [ 0,  0, -1]])
a@b.T
# насколько я понял, это единственный вариант.

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### b) Верхнетреугольная, ортогональная

In [130]:
g = np.array([[2, 6, 9],
              [1, 3, 5],
              [4, 5, 7]])
Q, R = LA.qr(g)

In [131]:
Q, R = LA.qr(g)

In [134]:
Q2, R2 = LA.qr(Q)

R2, R2@R2.T
# вроде подходит, но я не уверен, что это правильно.

(array([[ 1.00000000e+00,  1.11022302e-16,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]),
 array([[ 1.00000000e+00,  1.11022302e-16,  0.00000000e+00],
        [ 1.11022302e-16,  1.00000000e+00, -1.11022302e-16],
        [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00]]))

#### c) Нижнетреугольная, ортогональная

In [135]:
R2.T

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00]])

#### d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [136]:
b = np.array([[3, 2],
              [4, 3]])
LA.det(b)

1.0

In [141]:
c = np.array([[1, 1, 2],
              [2, 1, 1],
              [1, 1, 1]])
LA.det(c)

1.0

#### Найдите собственные значения и собственные вектора матриц:

In [143]:
m = np.array([[2, 2],
              [1, 3]])


In [144]:
w, v = LA.eig(m)

In [145]:
w

array([1., 4.])

In [146]:
v

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])